package Utilities;

public enum ServerRequest {
    TEACHER_LOGIN_REQUEST("2"), COMMENT_ADD_REQUEST("16"),
    COMMENT_FETCH_REQUEST("19"),
    QUESTION_FETCH_REQUEST("10"),
    QUIZ_ADD_REQUEST("11"),
    QUIZ_BY_STUDENT_REQUEST("17"),
    EXAM_LIST_FETCH_REQUEST("6"),
    QUESTION_LIST_FETCH_STUDENT_REQUEST("13"),
    QUIZ_LIST_FETCH_TEACHER_REQUEST("20"),
    EXAM_ADD_REQUEST("4"),
    SCORE_ADD_REQUEST("15"),
    SCORE_FETCH_REQUEST("14"),
    SECTION_ADD_REQUEST("7"),
    SECTION_FETCH_REQUEST("8"),
    SIGNUP_REQUEST("0"),
    STUDENT_LOGIN_REQUEST("1"),
     SUBJECT_ADD_REQUEST("3"),
    SUBJECT_LIST_FETCH_REQUEST("5"),
    QUESTION_ADD_REQUEST("9");
    ServerRequest(String s)
    {
        s.toString();
    }

}
